### ISSUE TITLE
create a simple UI to show the input and output image

### ISSUE THREAD

**Issue by Griffintaur** [Griffintaur/QRCodeReader#1]

**Comment by danielorf** [comment]
Are you thinking something like Tkinter or web-based (Flask)?  Web-based would also allow for an interface to select images rather than stashing them in a folder and pointing to it with a config file.

**Comment by Griffintaur** [comment]
I don't have much idea about Flask, but if you want to go for it, surely you can.
I don't have many preferences here.
Allowing User to select images for which he wants to see the code in execution is also a good idea.

**Comment by danielorf** [comment]
Did you end up making the UI update?  I'm still interested in helping -
it's just been a busy month since this was last discussed.

**Comment by Griffintaur** [comment]
sorry @danielorf for the last response,  but we got the simple UI using Flask.(PR #14 ) 
Since I am not good with UI, can u make the existing UI  better or any suggestion that you might have to improve it further, please do let me know you idea
