### ISSUE TITLE
Rewrite statements like `if A is None` to `if not A`.

### ISSUE THREAD

**Issue by suzil** [Griffintaur/QRCodeReader#7]
Statements like
```
if A is None:
    pass
```
Should be rewritten to the equivalent, but simpler
```
if not A:
    pass
```

**Comment by debugduck** [comment]
Hi, this is my first time contributing and I'd like to take this one. Is it still up for grabs?

**Comment by suzil** [comment]
@debugduck Go for it!

**Comment by Hemaolle** [comment]
Hi guys! Unfortunately it looks like later versions of `numpy` don't allow to test the truth value of arrays but fail with `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()` if you try to do that.

The old implementation of
```
if A is None:
    pass
```
works fine.

**Comment by Griffintaur** [comment]
@Hemaolle shall we revert the changes, or open a new issue?
which is more standard to use 
``` 
 if A is None :
     pass
```
or 
` if not A` with required changes?

**Comment by Hemaolle** [comment]
@Griffintaur, I'm not an expert in python conventions but I guess some of the changes in https://github.com/Griffintaur/QRCodeReader/pull/10 might have been good. I can make a new pull request to fix those cases where I had the error since I have that locally already.

**Comment by Hemaolle** [comment]
@Griffintaur there you go: https://github.com/Griffintaur/QRCodeReader/pull/13
